import PDFDocument from "pdfkit";
import { parseDataUrl } from "@/app/lib/gemini";
import type { EvidenceCheckItem } from "@/app/lib/types";

const STATUS_LABEL: Record<string, string> = {
  clean: "Clean",
  minor_concerns: "Minor concerns",
  needs_review: "Needs review",
  unusable: "Unusable",
};

const INK = "#0a0a0a";
const INK_SOFT = "#4b4b4b";
const LINE = "#e4e4e1";

// Built with pdfkit directly (the engine @react-pdf/renderer itself wraps),
// avoiding a React-reconciler element-identity conflict that @react-pdf/renderer
// hits when its components are compiled through Next's own bundled React copy.
export function renderEvidenceReportPdf(images: { base64: string; analysis: EvidenceCheckItem }[]): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 40 });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));

  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  doc.fontSize(18).fillColor(INK).text("Evidence Consistency — Full Report");
  doc
    .fontSize(10)
    .fillColor(INK_SOFT)
    .text(`${images.length} photo${images.length > 1 ? "s" : ""} · generated by PTP360 Second-Pass QA`);

  images.forEach((image, i) => {
    if (i > 0) doc.addPage();
    else doc.moveDown(1.5);

    const item = image.analysis;

    try {
      const { data } = parseDataUrl(image.base64);
      doc.image(Buffer.from(data, "base64"), { fit: [pageWidth, 320], align: "center" });
    } catch {
      doc.fontSize(10).fillColor(INK_SOFT).text("(image could not be embedded)");
    }
    doc.moveDown(0.75);

    if (item.error) {
      doc.fontSize(12).fillColor(INK).text("This photo couldn't be analyzed.");
      return;
    }

    const analysis = item.analysis;

    doc
      .fontSize(10)
      .fillColor(INK_SOFT)
      .text(analysis.detected_location ?? "Location unclear", { continued: true })
      .fillColor(INK)
      .text(`   ${STATUS_LABEL[analysis.overall.status]}`, { align: "left" });
    doc.moveDown(0.5);

    if (analysis.defect_signatures.length === 0) {
      doc.fontSize(11).fillColor(INK_SOFT).text("Nothing concerning was visible.");
    } else {
      for (const d of analysis.defect_signatures) {
        doc.fillColor(INK).fontSize(11).text(d.signature, { continued: true });
        doc.fillColor(INK_SOFT).fontSize(9).text(`   ${d.severity.toUpperCase()}`, { align: "left" });
        doc.fillColor(INK).fontSize(10).text(d.description);
        doc
          .fillColor(INK_SOFT)
          .fontSize(9)
          .text(
            `${d.region} · ${Math.round(d.confidence * 100)}% confidence · ${
              d.recommended_action === "flag_for_review" ? "Flag for review" : "Pass"
            }`
          );
        doc.moveDown(0.6);
      }
    }

    doc.moveDown(0.25);
    doc
      .strokeColor(LINE)
      .moveTo(doc.x, doc.y)
      .lineTo(doc.x + pageWidth, doc.y)
      .stroke();
    doc.moveDown(0.4);
    doc.fontSize(10).fillColor(INK).text(analysis.overall.summary, { continued: true });
    doc.fillColor(INK_SOFT).text(`   Risk ${analysis.overall.risk_score}/100`);
  });

  doc.end();
  return done;
}
